# Generated by Django 4.2.5 on 2023-09-28 06:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_category_user_task_priority'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Group',
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='category',
            new_name='group',
        ),
    ]
